/**
 * Pokémon Champions mechanics the calc engine doesn't know, applied only for
 * `gen9champions`:
 * - moves: Showdown's damage-relevant Champions changes (champions-moves.json,
 *   generated by gen-legal.ts) passed to the engine as Move overrides.
 * - abilities: Legends Z-A abilities rebuilt from engine abilities that apply the
 *   same modifier (verified against @smogon/calc), swapped in for one calc only.
 *
 * Not modeled: Protect interactions (Piercing Drill, Unseen Fist) and anything
 * that doesn't change a damage number (Spicy Spray, secondary chances, PP).
 */
import { toID } from '@pkmn/data';
import type { Field, Move, Pokemon } from '@smogon/calc/dist/adaptable';
import championsMoves from './champions-moves.json';

export const CHAMPIONS_FORMAT = 'gen9champions';

const MOVE_PATCH = championsMoves.patch as Record<string, object>;

/** Champions override data for a move, if Champions changed it. */
export function championsMoveOverrides(name: string): object | undefined {
  return MOVE_PATCH[toID(name)];
}

/** Abilities the engine lacks that are reproduced below. */
export const EMULATED_ABILITIES = new Set(['Fire Mane', 'Dragonize', 'Mega Sol', 'Aura Guard', 'Eelevate']);

// Dragonize leaves these Normal moves alone (Showdown's noModifyType list).
const NO_MODIFY_TYPE = new Set([
  'Judgment', 'Multi-Attack', 'Natural Gift', 'Revelation Dance', 'Techno Blast', 'Terrain Pulse', 'Weather Ball',
]);
const PRIMAL_WEATHER = new Set(['Harsh Sunshine', 'Heavy Rain', 'Strong Winds']);
// Non Fire/Water moves whose damage Sun changes.
const SUN_MOVES = new Set(['Weather Ball', 'Solar Beam', 'Solar Blade', 'Hydro Steam']);

export interface ChampionsSwap {
  /** [engine stand-in name, real ability name], for restoring the description. */
  swaps: [string, string][];
  /** Put every changed field back. */
  undo: () => void;
}

/**
 * Swap in the stand-ins for one calc, in place (clones would drop exact live
 * stats), and return how to restore them. Callers must `undo()` in a finally;
 * a throw part-way undoes itself.
 *
 * | Real | Side | When | Stand-in |
 * | Fire Mane | attacker | always (engine boosts only final Fire type, so Weather Ball in Sun counts) | Flash Fire, on |
 * | Dragonize | attacker | Normal move | move overrides: Dragon type at 4915/4096 bp |
 * | Mega Sol | attacker | move Sun affects, not primal weather | field weather Sun (2/3 bp if that erases a Sand/Snow defense boost) |
 * | Eelevate | both | always (airborne: no Ground hits, no terrain boost) | Levitate |
 * | Aura Guard | defender | contact move | Heatproof for Fire, Fluffy otherwise |
 */
export function applyChampionsMechanics(attacker: Pokemon, defender: Pokemon, move: Move, field: Field): ChampionsSwap {
  const undos: (() => void)[] = [];
  const swaps: [string, string][] = [];
  const undo = () => {
    while (undos.length) undos.pop()!();
  };
  const set = <T extends object, K extends keyof T>(obj: T, key: K, value: T[K]) => {
    const old = obj[key];
    obj[key] = value;
    undos.push(() => {
      obj[key] = old;
    });
  };
  const standIn = (mon: Pokemon, ability: string, on = false) => {
    swaps.push([ability, String(mon.ability)]);
    set(mon, 'ability', ability as Pokemon['ability']);
    set(mon, 'abilityOn', on);
  };

  try {
    switch (attacker.ability) {
      case 'Fire Mane':
        // Attacker only: on the defending side Flash Fire would add a Fire immunity.
        standIn(attacker, 'Flash Fire', true);
        break;
      case 'Dragonize':
        if (move.type === 'Normal' && !NO_MODIFY_TYPE.has(move.name)) {
          // The engine rebuilds the move from its name + overrides (calculate() clones
          // inputs), so the change must live in `overrides`, not on the Move fields.
          // ponytail: rounds at the BP step, not the chained 4915/4096 modifier (~1 damage off),
          // and misses moves whose power the engine computes itself (Crush Grip)
          const basePower = Math.round((move.bp * 4915) / 4096);
          set(move, 'overrides', { ...move.overrides, type: 'Dragon', basePower } as Move['overrides']);
        }
        break;
      case 'Mega Sol': {
        const w = field.weather ?? '';
        const sunMatters = move.type === 'Fire' || move.type === 'Water' || SUN_MOVES.has(move.name);
        if (!sunMatters || w === 'Sun' || PRIMAL_WEATHER.has(w)) break;
        set(field, 'weather', 'Sun' as Field['weather']);
        // The engine's Sun replaces Sand/Snow, erasing the defender's Sand (Rock, SpD) or
        // Snow (Ice, Def) 1.5x boost; cancel it at the base-power step.
        // ponytail: 2/3 bp for a 1.5x defense stat is off by ~1 point of base damage, a few % on
        // boosted super-effective hits; scale the defense stat instead if that matters
        const hitsDef = move.overrideDefensiveStat ? move.overrideDefensiveStat === 'def' : move.category === 'Physical';
        const lostBoost =
          (w === 'Sand' && defender.hasType('Rock') && !hitsDef) || (w === 'Snow' && defender.hasType('Ice') && hitsDef);
        if (lostBoost) {
          const basePower = Math.round((move.bp * 2) / 3);
          set(move, 'overrides', { ...move.overrides, basePower } as Move['overrides']);
        }
        break;
      }
      case 'Eelevate':
        standIn(attacker, 'Levitate');
        break;
    }

    switch (defender.ability) {
      case 'Aura Guard': {
        const contact =
          !!move.flags?.contact &&
          attacker.ability !== 'Long Reach' &&
          !(move.flags?.punch && attacker.item === 'Punching Glove');
        // ponytail: Heatproof halves Attack, not final damage, so Fire contact rolls can be 1 off
        if (contact) standIn(defender, move.type === 'Fire' ? 'Heatproof' : 'Fluffy');
        break;
      }
      case 'Eelevate':
        standIn(defender, 'Levitate');
        break;
    }
  } catch (e) {
    undo();
    throw e;
  }

  return { swaps, undo };
}
