/**
 * Single source of truth for dex data.
 *
 * Builds the Gen 9 `Generation` from @pkmn/dex and shares it with the
 * @smogon/calc *adaptable* engine (see calc.ts) so data is never shipped twice.
 *
 * VGC nuance: both SV-VGC and Champions-VGC run on the Gen 9 engine. SV has no
 * Mega Evolution, so @pkmn/data's default `exists` filter (which drops anything
 * flagged `isNonstandard`) correctly hides Megas. Champions RE-ENABLES Megas,
 * which are just `isNonstandard: 'Past'` formes already present in @pkmn/dex.
 * We admit those Mega/Primal formes back into the Gen 9 data layer so a single
 * data source can drive both formats. Newer Megas (`Future`: Z Megas,
 * Meowstic-M-Mega) are admitted only when their base is on the Champions
 * roster, and champions-dex-patch.json corrects fields the dex still lags on.
 */
import { Dex } from '@pkmn/dex';
import { Generations, type Generation, type Data } from '@pkmn/data';
import legalSpecies from './legal-species.json';
import dexPatch from './champions-dex-patch.json';
import { isMegaSpecies } from './mega';
import championsMoves from './champions-moves.json';
import { CHAMPIONS_FORMAT, EMULATED_ABILITIES } from './champions-mechanics';

export { isMegaSpecies };

// Pokémon Champions has its own dex: it includes species that left the Gen 9
// games (flagged `Past` here) and are otherwise dropped. Re-admit that roster so
// the data layer can represent them (see gen-legal.ts). Per-format pickers still
// gate on the same list, so Champions mons don't leak into OU/Doubles.
const CHAMPIONS_IDS = new Set((legalSpecies as Record<string, string[]>).gen9champions ?? []);
const CHAMPIONS_MOVES = new Set(championsMoves.admit);

const toId = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

type NonstandardSpecies = {
  id: string;
  isNonstandard: string;
  baseSpecies: string;
  changesFrom?: string;
  isMega?: boolean;
  isPrimal?: boolean;
  forme?: string;
};

/** DEFAULT_EXISTS, plus: keep Mega/Primal formes and the Champions roster. */
function existsWithMegas(d: Data): boolean {
  if (!d.exists) return false;
  if ('isNonstandard' in d && d.isNonstandard) {
    // Re-admit Megas and Champions-roster species (`Past` in Gen 9); reject
    // everything else (items included: stones never reach the calc).
    // Moves Champions re-enables (Meteor Assault, Snap Trap...), so they can be
    // calculated; allMoves() hides them outside Champions.
    if (d.kind === 'Move') return CHAMPIONS_MOVES.has(d.id);
    if (d.kind !== 'Species') return false;
    const sp = d as unknown as NonstandardSpecies;
    if (!isMegaSpecies(sp)) return CHAMPIONS_IDS.has(sp.id);
    // Classic Megas always; newer ones only off a Champions-roster base, so
    // Z-A-only Megas (Tatsugiri-Curly-Mega) stay out.
    return (
      sp.isNonstandard === 'Past' ||
      [sp.changesFrom, sp.baseSpecies].some((n) => n !== undefined && CHAMPIONS_IDS.has(toId(n)))
    );
  }
  if (d.kind === 'Ability' && d.id === 'noability') return false;
  return !('tier' in d && ['Illegal', 'Unreleased'].includes((d as { tier: string }).tier));
}

// @pkmn/dex lags new regulations (Reg M-C Z Mega abilities). Overlay the fields
// where Showdown's Champions data differs, generated by gen-legal.ts. Must run
// before the Generation is built.
// ponytail: patches the shared Gen 9 dex, so OU sees it too; harmless, those formes are illegal there.
for (const [id, fields] of Object.entries(dexPatch)) {
  const sp = Dex.forGen(9).species.get(id);
  if (sp?.exists) Object.assign(sp as object, fields);
}

const gens = new Generations(Dex, existsWithMegas);

/** The shared Gen 9 generation, with classic Megas available as formes. */
export const gen: Generation = gens.get(9);

// Full dex option lists (memoized) — for manual overrides when usage data is
// missing, so any legal item/move/type/ability can still be chosen.
let itemsCache: string[] | null = null;
let movesCache: string[] | null = null;
let typesCache: string[] | null = null;

export function allItems(): string[] {
  if (!itemsCache) itemsCache = Array.from(gen.items, (i) => i.name).sort();
  return itemsCache;
}

// Mega Stones / Primal Orbs, derived from the formes that require them. Surfaced
// first in the item picker for Mega formats (Champions), where they matter and
// there's no usage data to rank by.
let megaStoneCache: string[] | null = null;
export function megaStones(): string[] {
  if (megaStoneCache) return megaStoneCache;
  const s = new Set<string>();
  for (const sp of gen.species) {
    if (isMegaSpecies(sp) && sp.requiredItem) s.add(sp.requiredItem);
  }
  megaStoneCache = [...s].sort();
  return megaStoneCache;
}
let otherMovesCache: string[] | null = null;
/** Every move in the dex; Champions-only re-enabled moves only for Champions. */
export function allMoves(formatId?: string): string[] {
  if (!movesCache) movesCache = Array.from(gen.moves, (m) => m.name).sort();
  if (formatId === CHAMPIONS_FORMAT) return movesCache;
  otherMovesCache ??= movesCache.filter((n) => !CHAMPIONS_MOVES.has(toId(n)));
  return otherMovesCache;
}
export function allTypes(): string[] {
  if (!typesCache) typesCache = Array.from(gen.types, (t) => t.name).filter((n) => n !== '???').sort();
  return typesCache;
}
/** The species' possible abilities (slots 0/1/Hidden). */
export function abilitiesFor(species: string): string[] {
  const sp = gen.species.get(species);
  return sp ? (Object.values(sp.abilities).filter(Boolean) as string[]) : [];
}

/** False for an ability the calc can't apply: unknown to the dex and not emulated for this format. */
export function isModeledAbility(name?: string, formatId?: string): boolean {
  return !name || !!gen.abilities.get(name) || (formatId === CHAMPIONS_FORMAT && EMULATED_ABILITIES.has(name));
}

/** The Mega Stone / Orb a forme requires to exist, if any (else undefined). */
export function requiredItemFor(species: string): string | undefined {
  const sp = gen.species.get(species);
  return sp && isMegaSpecies(sp) ? sp.requiredItem : undefined;
}

// Per-format legal held items (by name). A format absent here is unrestricted
// (whole item dex); only Champions limits items. See gen-legal.ts.
import legalItemsJson from './legal-items.json';
const LEGAL_ITEMS = legalItemsJson as Record<string, string[]>;
export function legalItems(formatId?: string): string[] | null {
  return (formatId && LEGAL_ITEMS[formatId]) || null;
}
